# Generated by Django 2.1.4 on 2018-12-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_goods_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='stock',
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(default=0, verbose_name='stock number'),
        ),
    ]
