# Generated by Django 2.1.4 on 2018-12-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goodsimage'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Goods',
            new_name='OrderGoods',
        ),
    ]
