# Generated by Django 2.1.4 on 2018-12-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verifycode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user Profile', 'verbose_name_plural': 'user Profile'},
        ),
    ]
