# Generated by Django 2.1.4 on 2019-01-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190109_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('forum.comments', 'get comments'), ('view_comments', 'view comments')), 'verbose_name': 'user Profile', 'verbose_name_plural': 'user Profile'},
        ),
    ]
