# Generated by Django 2.1.4 on 2019-01-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190109_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='name')),
            ],
            options={
                'permissions': (('forum.comments', 'get comments'), ('view_comments', 'view comments')),
            },
        ),
    ]
