# Generated by Django 2.1.4 on 2019-01-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_citizen_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
