# Generated by Django 2.1.4 on 2019-01-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='link',
            new_name='image',
        ),
    ]
